services:
  - type: web
    name: fd-advisory-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt && python train_model.py"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
    rootDir: backend
